// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projeto_API.DataServices;

namespace Projeto_API.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Projeto_API.Entities.Cliente", b =>
                {
                    b.Property<Guid>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_cliente")
                        .HasDefaultValueSql("newsequentialid()");

                    b.Property<string>("Cpf")
                        .HasMaxLength(1000)
                        .HasColumnType("VARCHAR(1000)")
                        .HasColumnName("cpf");

                    b.Property<DateTime>("DataExpedicao")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_expedicao");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_nascimento");

                    b.Property<string>("EstadoCivilDesc")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("estado_civil_desc");

                    b.Property<int>("EstadoCivilValue")
                        .HasColumnType("int")
                        .HasColumnName("estado_civil_value");

                    b.Property<string>("Nome")
                        .HasMaxLength(1000)
                        .HasColumnType("VARCHAR(1000)")
                        .HasColumnName("nome");

                    b.Property<string>("OrgaoExpedicaoDesc")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("orgao_expedicao_desc");

                    b.Property<int>("OrgaoExpedicaoValue")
                        .HasColumnType("int")
                        .HasColumnName("orgao_expedicao_value");

                    b.Property<string>("Rg")
                        .HasMaxLength(25)
                        .HasColumnType("VARCHAR(25)")
                        .HasColumnName("rg");

                    b.Property<string>("SexoDesc")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sexo_desc");

                    b.Property<int>("SexoValue")
                        .HasColumnType("int")
                        .HasColumnName("sexo_value");

                    b.HasKey("IdCliente");

                    b.ToTable("cliente");
                });

            modelBuilder.Entity("Projeto_API.Entities.EnderecoCliente", b =>
                {
                    b.Property<Guid>("IdEnderecoCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_endereco_cliente")
                        .HasDefaultValueSql("newsequentialid()");

                    b.Property<string>("Bairro")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("bairro");

                    b.Property<string>("Cep")
                        .HasMaxLength(1000)
                        .HasColumnType("VARCHAR(1000)")
                        .HasColumnName("cep");

                    b.Property<string>("Cidade")
                        .HasMaxLength(250)
                        .HasColumnType("VARCHAR(250)")
                        .HasColumnName("cidade");

                    b.Property<string>("Complemento")
                        .HasMaxLength(1000)
                        .HasColumnType("VARCHAR(1000)")
                        .HasColumnName("complemento");

                    b.Property<string>("EstadoDesc")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("uf_desc");

                    b.Property<int>("EstadoValue")
                        .HasColumnType("int")
                        .HasColumnName("uf_value");

                    b.Property<Guid>("IdCliente")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id_cliente");

                    b.Property<string>("Numero")
                        .HasMaxLength(1000)
                        .HasColumnType("VARCHAR(1000)")
                        .HasColumnName("numero");

                    b.Property<string>("Rua")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("rua");

                    b.HasKey("IdEnderecoCliente");

                    b.HasIndex("IdCliente")
                        .IsUnique();

                    b.ToTable("endereco_cliente");
                });

            modelBuilder.Entity("Projeto_API.Entities.EnderecoCliente", b =>
                {
                    b.HasOne("Projeto_API.Entities.Cliente", "Cliente")
                        .WithOne("Endereco")
                        .HasForeignKey("Projeto_API.Entities.EnderecoCliente", "IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Projeto_API.Entities.Cliente", b =>
                {
                    b.Navigation("Endereco");
                });
#pragma warning restore 612, 618
        }
    }
}
